In [2]:
import nltk
nltk.download('movie_reviews')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     /Users/daalvare/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.


True

In [3]:
#https://stackoverflow.com/questions/48003907/how-to-train-naive-bayes-classifier-for-n-gram-movie-reviews
import nltk.classify.util
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import movie_reviews
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import ngrams

def create_ngram_features(words, n=2):
    ngram_vocab = ngrams(words, n)
    my_dict = dict([(ng, True) for ng in ngram_vocab])
    return my_dict

for n in [1,2,3,4,5]:
    pos_data = []
    for fileid in movie_reviews.fileids('pos'):
        words = movie_reviews.words(fileid)
        pos_data.append((create_ngram_features(words, n), "positive"))    

    neg_data = []
    for fileid in movie_reviews.fileids('neg'):
        words = movie_reviews.words(fileid)
        neg_data.append((create_ngram_features(words, n), "negative")) 

    train_set = pos_data[:800] + neg_data[:800]
    test_set =  pos_data[800:] + neg_data[800:]

    classifier = NaiveBayesClassifier.train(train_set)

    accuracy = nltk.classify.util.accuracy(classifier, test_set)
    print(str(n)+'-gram accuracy:', accuracy)

1-gram accuracy: 0.735
2-gram accuracy: 0.7625
3-gram accuracy: 0.8275
4-gram accuracy: 0.8125
5-gram accuracy: 0.74


In [201]:
import importlib
sys.path.append('../src/')

In [ ]:
outdir = '../src/out/movies/'

In [88]:
def unfeaturize(featureset):
    keys = list(featureset.keys())
    string = list(keys[0])
    for i,gram in enumerate(keys):
        if i == 0: continue
        string += [gram[-1]]
    return ' '.join(string)

unfeaturize(test_set[0][0])

"those of you who frequently read my reviews are not likely to be surprised by the fact that i have not read victor hugo ' s novel les miserables . i don ' t know if a lot of people have , though i imagine many are familiar with the popular musical based on the novel . i haven ' t even seen that . going into this film , i had almost no knowledge of the story or its characters ( i even expected the film to be a musical ) . walking away from it , i ' m kind of glad i had no prior experience with the material . writer / director bille august ' s film version is a straightforward , beautifully told film . liam neeson stars as the miserable jean valjean ; in the beginning , he has just been released from a 19 - year prison sentence . he is allowed to stay in a convent by a kindly priest despite his rude and destructive behavior . the priest ' s words of wisdom influence him , and he makes a vow to change himself . nine years later , we are informed that he is now the mayor of a town called 

In [107]:
i = 5
x, y = test_set[i]
print(y)
unfeaturize(x)

positive


'after sixteen years francis ford copolla has again returned to his favorite project , making the third installment in the godfather - trilogy . this new film has been underrated for no reason . it is as intellectual and majestically made as copolla \' s pervious films . it is also more psychological , pessimistic and more tragic than the first two . the only regret is the unconvincing performance by the newcomer sofia copolla and some " unfinished " developments of some characters . the film elegantly begins with nino rota \' s recognizable musical score , the beautiful skyscrapers of new york and michael \' s voice as he is writing a letter to his children : " the only wealth in this world is children . more than all money and power on earth , you are my treasure " . the year is 1979 and michael corleone has used the time since the ending of " part ii " to make his father \' s dream come true - making the corleone family legitimate . michael sold all his casinos and invests only in g

In [116]:
p = classifier.prob_classify(x)
print(p.prob('negative'),p.prob('positive'))

print(classifier.most_informative_features(), 10)

#classifier._feature_probdist[list(x.keys())[0]]

0.998942917547577 0.0010570824524312968
[(('.', 'then', 'there', "'", 's'), True), (('one', 'of', 'the', 'best', 'films'), True), (('be', 'one', 'of', 'the', 'most'), True), (('.', 'the', 'supporting', 'cast', 'is'), True), (('that', "'", 's', 'not', 'the'), True), (('we', "'", 're', 'supposed', 'to'), True), (('the', 'best', 'films', 'of', 'the'), True), (('if', 'you', "'", 're', 'going'), True), (('.', 'it', "'", 's', 'as'), True), (('is', 'one', 'of', 'the', 'few'), True), (('it', "'", 's', 'as', 'if'), True), (('one', 'of', 'the', 'best', 'movies'), True), (('it', "'", 's', 'just', 'not'), True), (('is', 'one', 'of', 'the', 'worst'), True), (('.', 'here', "'", 's', 'the'), True), (('i', "'", 'm', 'not', 'saying'), True), (('to', 'fall', 'in', 'love', 'with'), True), ((',', 'and', 'as', 'a', 'result'), True), (('it', 'isn', "'", 't', '.'), True), (('towards', 'the', 'end', 'of', 'the'), True), (('as', 'if', 'he', "'", 's'), True), (('just', 'doesn', "'", 't', 'work'), True), (('down

In [114]:
classifier._feature_probdist

{('positive',
  ('films',
   'adapted',
   'from',
   'comic',
   'books')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('adapted',
   'from',
   'comic',
   'books',
   'have')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('from',
   'comic',
   'books',
   'have',
   'had')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('comic',
   'books',
   'have',
   'had',
   'plenty')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('books',
   'have',
   'had',
   'plenty',
   'of')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('have',
   'had',
   'plenty',
   'of',
   'success')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('had', 'plenty', 'of', 'success', ',')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('plenty',
   'of',
   'success',
   ',',
   'whether')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('of',
   'success',
   ',',
   'whether',
   'they')): <ELEProbDist based on 800 samples>,
 ('positive',
  ('success',
 

In [18]:
documents = [(list(movie_reviews.words(fileid)), category) 
             for category in movie_reviews.categories()
             for fileid in movie_reviews.fileids(category)]

In [59]:
x_text, x_score = documents[-4]
print(x_text[:5])

['richard', 'gere', 'can', 'be', 'a']


In [64]:
create_ngram_features(x_text, 4)

{('richard', 'gere', 'can', 'be'): True,
 ('gere', 'can', 'be', 'a'): True,
 ('can', 'be', 'a', 'commanding'): True,
 ('be', 'a', 'commanding', 'actor'): True,
 ('a', 'commanding', 'actor', ','): True,
 ('commanding', 'actor', ',', 'but'): True,
 ('actor', ',', 'but', 'he'): True,
 (',', 'but', 'he', "'"): True,
 ('but', 'he', "'", 's'): True,
 ('he', "'", 's', 'not'): True,
 ("'", 's', 'not', 'always'): True,
 ('s', 'not', 'always', 'in'): True,
 ('not', 'always', 'in', 'great'): True,
 ('always', 'in', 'great', 'films'): True,
 ('in', 'great', 'films', '.'): True,
 ('great', 'films', '.', 'everything'): True,
 ('films', '.', 'everything', 'comes'): True,
 ('.', 'everything', 'comes', 'together'): True,
 ('everything', 'comes', 'together', 'here'): True,
 ('comes', 'together', 'here', '.'): True,
 ('together', 'here', '.', 'gere'): True,
 ('here', '.', 'gere', 'is'): True,
 ('.', 'gere', 'is', 'a'): True,
 ('gere', 'is', 'a', 'big'): True,
 ('is', 'a', 'big', 'time'): True,
 ('a', 'bi

In [63]:
p = classifier.classify(create_ngram_features(x_text, 4))
print(p)
# type(p)
# print(dir(p))
# print(p.max())
# p.samples()
# print(p.prob('positive'), p.prob('negative'))

positive
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


AttributeError: 'str' object has no attribute 'max'

In [46]:
p.prob()

TypeError: prob() missing 1 required positional argument: 'sample'

In [31]:
movie_reviews.words('neg/cv999_14636.txt')

['two', 'party', 'guys', 'bob', 'their', 'heads', 'to', ...]

In [33]:
tst[0]

['steven',
 'spielberg',
 "'",
 's',
 'second',
 'epic',
 'film',
 'on',
 'world',
 'war',
 'ii',
 'is',
 'an',
 'unquestioned',
 'masterpiece',
 'of',
 'film',
 '.',
 'spielberg',
 ',',
 'ever',
 'the',
 'student',
 'on',
 'film',
 ',',
 'has',
 'managed',
 'to',
 'resurrect',
 'the',
 'war',
 'genre',
 'by',
 'producing',
 'one',
 'of',
 'its',
 'grittiest',
 ',',
 'and',
 'most',
 'powerful',
 'entries',
 '.',
 'he',
 'also',
 'managed',
 'to',
 'cast',
 'this',
 'era',
 "'",
 's',
 'greatest',
 'answer',
 'to',
 'jimmy',
 'stewart',
 ',',
 'tom',
 'hanks',
 ',',
 'who',
 'delivers',
 'a',
 'performance',
 'that',
 'is',
 'nothing',
 'short',
 'of',
 'an',
 'astonishing',
 'miracle',
 '.',
 'for',
 'about',
 '160',
 'out',
 'of',
 'its',
 '170',
 'minutes',
 ',',
 '"',
 'saving',
 'private',
 'ryan',
 '"',
 'is',
 'flawless',
 '.',
 'literally',
 '.',
 'the',
 'plot',
 'is',
 'simple',
 'enough',
 '.',
 'after',
 'the',
 'epic',
 'd',
 '-',
 'day',
 'invasion',
 '(',
 'whose',
 'seq

# Breast Cancer

In [304]:
import sklearn.datasets
data = sklearn.datasets.load_breast_cancer()
X = data['data']
Y = data['target']
X_names = data['feature_names']
Y_names = data['target_names']
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [305]:
X_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [306]:
# reorder features by attribute
attrib_order = [j for sublist in [[i, i+10, i+20] for i in range(10)] for j in sublist]
print(attrib_order)
X = X[:,attrib_order]
X_names = X_names[attrib_order]
print(X_names)

# Data Split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

attributes = np.split(np.arange(30), 10)
attribute_names = ['radius', 'texture', 'perimeter', 'area','smoothness',
                'compactness', 'concavity', 'concave points', 'symmetry', 'fractal dimension']

[0, 10, 20, 1, 11, 21, 2, 12, 22, 3, 13, 23, 4, 14, 24, 5, 15, 25, 6, 16, 26, 7, 17, 27, 8, 18, 28, 9, 19, 29]
['mean radius' 'radius error' 'worst radius' 'mean texture'
 'texture error' 'worst texture' 'mean perimeter' 'perimeter error'
 'worst perimeter' 'mean area' 'area error' 'worst area' 'mean smoothness'
 'smoothness error' 'worst smoothness' 'mean compactness'
 'compactness error' 'worst compactness' 'mean concavity'
 'concavity error' 'worst concavity' 'mean concave points'
 'concave points error' 'worst concave points' 'mean symmetry'
 'symmetry error' 'worst symmetry' 'mean fractal dimension'
 'fractal dimension error' 'worst fractal dimension']


### Prediction via density estimation - via Scikit-Learn

In [292]:
import numpy as np
import sklearn.naive_bayes

classifier = sklearn.naive_bayes.GaussianNB()
classifier.fit(X_train, Y_train)
print(classifier.score(X_test, Y_test))

# Returns P(Y|X)
print(classifier.predict_proba(X_test)[:10])

# Returns unnormalized cond prob:  log P(X |Y )  + log P(Y)
print(classifier._joint_log_likelihood(X_test)[:10])

# To get priors
priors = [np.log(classifier.class_prior_[i]) for i in range(np.size(classifier.classes_))]
print('Priors', priors)

# To get just conditional log-likelihhod
cond_ll = []
for i in range(np.size(classifier.classes_)):
    n_ij = - 0.5 * np.sum(np.log(2. * np.pi * classifier.sigma_[i, :]))
    n_ij -= 0.5 * np.sum(((X_test - classifier.theta_[i, :]) ** 2) /
                         (classifier.sigma_[i, :]), 1)
    cond_ll.append(n_ij)
print('Cond ll : 0 ', cond_ll[0][:10])
print('Cond ll : 1 ', cond_ll[1][:10])




0.916083916083916
[[1.00000000e+00 7.14272482e-11]
 [1.66160798e-14 1.00000000e+00]
 [1.52718888e-15 1.00000000e+00]
 [1.01878249e-13 1.00000000e+00]
 [1.48055213e-17 1.00000000e+00]
 [1.05040989e-14 1.00000000e+00]
 [9.23728704e-12 1.00000000e+00]
 [2.64356434e-16 1.00000000e+00]
 [1.18541864e-16 1.00000000e+00]
 [8.20428719e-19 1.00000000e+00]]
[[-34.13303795 -57.49537964]
 [-54.74122816 -23.01282266]
 [-57.98964078 -23.8742931 ]
 [-57.69512899 -27.78013105]
 [-64.89497617 -26.14344466]
 [-50.65311838 -18.46610754]
 [-55.84437609 -30.43660321]
 [-57.83550927 -21.96627592]
 [-84.90738125 -48.23611576]
 [-75.60337611 -33.95891619]]
Priors [-0.9855351440491389, -0.4671906878691208]
Cond ll : 0  [-33.14750281 -53.75569302 -57.00410564 -56.70959385 -63.90944102
 -49.66758324 -54.85884095 -56.84997413 -83.92184611 -74.61784097]
Cond ll : 1  [-57.02818896 -22.54563197 -23.40710241 -27.31294037 -25.67625398
 -17.99891685 -29.96941252 -21.49908523 -47.76892507 -33.49172551]


In [307]:
from woe_utils import woe_wrapper

class woe_scikit_gnb(woe_wrapper):
    """
        WOE Wrapper around scikit GNB classifier
    """
    def __init__(self, clf, task=None, classes=None, input_size=None):
        super().__init__(clf, task, classes, input_size)
        self.cond_type = 'nb'
    
    def log_prob(self, x, y):
        """ 
        """
        # Lazy approach: subtract prior from joint_log_likelihood = log P(X |Y )  + log P(Y)
        #return self.model._joint_log_likelihood(x)[:,y] - self.model.class_prior_[y]        
        # If want to compute manually, can do:
        n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.model.sigma_[y, :]))
        n_ij -= 0.5 * np.sum(((x - self.model.theta_[y, :]) ** 2) /
                         (self.model.sigma_[y,:]), 1)          
        return n_ij     


    def log_prob_partial(self, subset, x, y):
        # Using naive Bayes, we do P(X_s | X_s1,...X_s, Y) = P (X_s, Y)
        # for GNB, this is easy: just drop non-included vars
        # en.wikipedia.org/wiki/Multivariate_normal_distribution#Marginal_distributions        
        n_ij = - 0.5 * np.sum(np.log(2. * np.pi * self.model.sigma_[y, subset]))
        n_ij -= 0.5 * np.sum(((x[:,subset] - self.model.theta_[y, subset]) ** 2) /
                         (self.model.sigma_[y, subset]), 1)          
        return n_ij
    
    def generalized_conditional_ll(self, x, y, subset=None, verbose = False, **kwargs):
        ## TODO: either make a non-torch version of the equivalent method in wrapper, or transsfortm to torch and use that one
        if subset is None:
            return self.log_prob(x, y)
        else:
            return self.log_prob_partial(subset, x, y)
#         elif self.cond_type == 'nb':

#             print('jere')
#             return self.model._joint_log_likelihood(x)[:,y] - self.model.class_prior_[y]
        

woe_model = woe_scikit_gnb(classifier, classes = [0,1])

print(woe_model.log_prob(X_test,0)[:10])

np.allclose(woe_model.log_prob(X_test,0), woe_model.log_prob_partial(np.arange(30), X_test, 0))

[-33.14750281 -53.75569302 -57.00410564 -56.70959385 -63.90944102
 -49.66758324 -54.85884095 -56.84997413 -83.92184611 -74.61784097]


True

In [346]:
### Choose an test example to explain
idx = 13

In [347]:
# Compute partial and total woe

def explain(x):
    partial_woes = []
    for attribute in attributes:
        partial_woes.append(woe_model.woe(x, 1, 0, subset=attribute))

    partial_woes = np.array(partial_woes)
    total_woe = woe_model.woe(x, 1, 0)[0]
    prior_odds = np.log(classifier.class_prior_[1] - classifier.class_prior_[0])
    
    sorted_partial_woes= [(i,x[0]) for x,i in sorted(zip(partial_woes,range(len(attributes))), reverse=True)]
    print('Example index: {}'.format(idx))
    print('Prediction: {}'.format('positive' if classifier.predict(x)[0] else 'negative'))
    print('Bayes odds explanation:\n')
    print('   {:8.2f}     =        {:8.2f}  +  {:<8.2f}'.format(prior_odds + total_woe, prior_odds, total_woe))
    print('post. log-odds  =  prior log-odds  +  total_woe')
    
    print('\nTotal WoE in favor of Positive: {:8.2f}'.format(total_woe))
    
    for i,woe in sorted_partial_woes:
        print('woe({:>20}) = {:8.2f}'.format(attribute_names[i], woe))
        
    print('     {:>20} = {:8.2f}'.format('sum', partial_woes.sum()))

explain(X_test[idx:idx+1])

Example index: 13
Prediction: negative
Bayes odds explanation:

      -6.27     =           -1.37  +  -4.90   
post. log-odds  =  prior log-odds  +  total_woe

Total WoE in favor of Positive:    -4.90
woe(      concave points) =     4.83
woe(          smoothness) =     3.35
woe(         compactness) =     2.77
woe(           concavity) =     2.31
woe(            symmetry) =     1.09
woe(   fractal dimension) =     0.40
woe(             texture) =     0.15
woe(              radius) =    -5.33
woe(           perimeter) =    -5.57
woe(                area) =    -8.92
                      sum =    -4.90


In [300]:
len(attribute_names)

9

In [317]:
total_woe

array([-19.76653651])

### Prediction via density estimation - manual

In [164]:
from sklearn.neighbors.kde import KernelDensity

KDE = {}
KDE['unconditional'] = KernelDensity(kernel='gaussian', bandwidth=0.5).fit(X_train) 
for cl in [0,1]:
    KDE[cl] = KernelDensity(kernel='gaussian', bandwidth=0.5).fit(X_train[Y_train==cl])
    print('Class = {}'.format(cl))    
    print(KDE[cl].score_samples(X_train[Y_train==cl]).mean())
    print(KDE[cl].score_samples(X_test[Y_test==cl]).mean())
    print(KDE[cl].score_samples(X_train[Y_train!=cl]).mean())
    print(KDE[cl].score_samples(X_test[Y_test!=cl]).mean())


Class = 0
-11.840842913387617
-37.77107402884194
-39.38239910564196
-39.79968708631501
Class = 1
-12.348827987575444
-22.653397407516007
-76.1107668459036
-78.23896845330238


In [162]:
# Compute Priors
class_priors = {k: (Y_train==k).sum() for k in set(Y)} 
print(class_priors)

{0: 159, 1: 267}


In [173]:
class density_classifier():
    def __init__(self, density_type = 'kde'):
        self.density_type = 'kde'
        #dm = density_model
        #classes = class_priors.keys()
        #priors = class_priors
        
    def predict(self, x):
        probs = {}
        px  = self.dm['unconditional'].score_samples(x)
        for c in self.classes:
            # p(y | X) *= P(X | y)P(Y)
            pxy = self.dm[cl].score_samples(x)
            py  = self.class_priors[c]
            probs[c] = pxy*py/px
            
        return probs
    
    def fit(self, X, Y):
        self.classes = list(set(Y))
        dm= {}
        if self.density_type == 'kde':
            _density_model = sklearn.neighbors.kde.KernelDensity
        dm = {cl: _density_model(kernel='gaussian', bandwidth=0.5).fit(X_train[Y_train==cl]) for cl in self.classes}
        dm['unconditional'] = _density_model(kernel='gaussian', bandwidth=0.5).fit(X_train) 
        #print('Class = {}'.format(cl))    
        #print(KDE[cl].score_samples(X_train[Y_train==cl]).mean())
        #print(KDE[cl].score_samples(X_test[Y_test==cl]).mean())
        #print(KDE[cl].score_samples(X_train[Y_train!=cl]).mean())
        #print(KDE[cl].score_samples(X_test[Y_test!=cl]).mean())
        self.dm = dm
        self.class_priors = {k: (Y_train==k).sum()/len(Y) for k in self.classes} 
        print(self.class_priors)

    
classifier = density_classifier('kde')
classifier.fit(X_train, Y_train)

classifier.predict(X_test[:5,:])

{0: 0.3732394366197183, 1: 0.6267605633802817}


{0: array([0.50646556, 0.3654826 , 0.36250703, 0.36183733, 0.36648686]),
 1: array([0.8504799 , 0.61373493, 0.60873823, 0.60761363, 0.61542133])}

[-33.14750281 -53.75569302 -57.00410564 -56.70959385 -63.90944102
 -49.66758324 -54.85884095 -56.84997413 -83.92184611 -74.61784097]


True

In [268]:
print(classifier._joint_log_likelihood(X_test).shape)
print(woe_model.log_prob(X_test, 0).shape)


(143, 2)
(143,)


In [269]:
list(zip(woe_model.woe(X_test, 0, 1), Y_test))

[(23.88068614812756, 0),
 (-31.21006104811831, 1),
 (-33.5970032244615, 1),
 (-29.39665347983319, 1),
 (-38.23318704632057, 1),
 (-31.66866638750096, 1),
 (-24.889428427466463, 1),
 (-35.35088889463039, 1),
 (-36.15292103947599, 1),
 (-41.1261154654197, 1),
 (19.766536507434168, 1),
 (-21.154745158650968, 1),
 (-34.275520528794736, 1),
 (4.9024410972416845, 1),
 (8.166851353200109, 1),
 (45.849706477616145, 0),
 (1.9895811994072687, 1),
 (133.96508987317173, 0),
 (99.16515293831412, 0),
 (295.65851459209654, 0),
 (40.06830956760836, 0),
 (41.58441809827385, 0),
 (-19.559247631840172, 1),
 (-35.91640862637914, 1),
 (116.68042243234555, 0),
 (-39.59451981106047, 1),
 (-47.57164120052401, 1),
 (58.96084477424691, 0),
 (-34.16097649118688, 1),
 (146.87656705448694, 0),
 (-42.045251420768864, 1),
 (128.59916958055516, 0),
 (-13.9940294167289, 1),
 (26.219326569281034, 0),
 (-46.49650919135443, 1),
 (15.057295653461217, 0),
 (-29.946011097400024, 1),
 (96.01425987390977, 0),
 (-25.6262285082

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]
[27 28 29]
[[-0.93167667]
 [ 8.4955873 ]
 [ 1.86381337]
 [ 1.6289945 ]
 [ 0.94126988]
 [ 2.09970456]
 [ 4.71270004]
 [-0.17944542]
 [ 1.85861146]
 [-0.72302251]]


In [264]:
woe_model.woe(X_test[idx:idx+1,:], 0, 1, subset=attribute).shape

(143,)

In [266]:
X_test[idx:idx+1,:].shape

(1, 30)

In [328]:
classifier.class_prior_[0]

0.3732394366197183